### ISSUE TITLE
charts.openshift.io website should link this Git repository somewhere

### ISSUE THREAD

**Issue by jerolimov** [openshift-helm-charts/charts#549] opened 2022-08-04 16:07 UTC
When researching an issue with a Helm Chart I quickly found the `HelmChartRepository` that refers https://charts.openshift.io

But the website doesn't contain any references where I can create a bug or research the existing bug reports, PR or source code.

It would be great if the website contains a reference https://github.com/openshift-helm-charts/charts or so.

**Comment by komish** [comment] 2023-04-18 16:40
Closing as a duplicate of #407

**Closed by komish** 2023-04-18 16:40 UTC
